# Horizontal Pod Autoscaler for desktop servers
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: desktop-xfce-hpa
  namespace: lumadesk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: desktop-xfce
  minReplicas: 3
  maxReplicas: 20  # Max 1500 users (20 x 75)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 2
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Pods
        value: 1
        periodSeconds: 180
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: desktop-kde-hpa
  namespace: lumadesk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: desktop-kde
  minReplicas: 2
  maxReplicas: 15  # Max 750 users (15 x 50)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: desktop-gnome-hpa
  namespace: lumadesk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: desktop-gnome
  minReplicas: 2
  maxReplicas: 15  # Max 750 users (15 x 50)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
